using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

public class PlayerController : MonoBehaviour
{
    private PlayerActions playerInput;
    private Rigidbody2D rb;
    public bool isPaused = false; // pour l'UI

    [SerializeField] private float speed = 10.0f;

    private void Awake()
    {
        playerInput = new PlayerActions();
        rb = GetComponent<Rigidbody2D>();
    }

    private void OnEnable()
    {
        playerInput.Enable();
    }

    private void OnDisable()
    {
        playerInput.Disable();
    }


    private void Pause()
    {
        if (Time.timeScale == 1f && isPaused == false)
        {
            Time.timeScale = 0f;
        }
        else if (Time.timeScale == 0f && isPaused == true)
        {
            Time.timeScale = 1f;
        }
    }

    void FixedUpdate() // utilisation de la physics
    {
        Vector2 moveInput = playerInput.Gameplay.Movement.ReadValue<Vector2>();
        rb.velocity = moveInput * speed;

    }

    //private void Update()
    //{
    //    if (playerInput.Gameplay.Pause.triggered)
    //    {
    //        Pause();
    //        isPaused = !isPaused;
    //    }
//    }
//}

    
}